# version: "3.9"
---
services:
  telegram_youtube_bot:
    build:
      context: .
      dockerfile: telegram_youtube_bot/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    container_name: ${STACK_PREFIX}_telegram_bot
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_IDS=${TELEGRAM_ADMIN_IDS}
      - YT_DLP_COOKIES_FILE=${YT_DLP_COOKIES_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - DOMAIN=${DOMAIN}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # Google Drive integration
      - GOOGLE_DRIVE_COOKIES_FILE_ID=${GOOGLE_DRIVE_COOKIES_FILE_ID}
      - GOOGLE_DRIVE_SERVICE_ACCOUNT=${GOOGLE_DRIVE_SERVICE_ACCOUNT}
      - GOOGLE_DRIVE_REFRESH_INTERVAL=${GOOGLE_DRIVE_REFRESH_INTERVAL}
    volumes:
      - input:/input
      - metadata:/metadata
      - cookies:/cookies:rw    # <--- Use named volume, not host path, for permissions
    networks:
      - backend
    depends_on:
      volume-init:
        condition: service_completed_successfully

volumes:
  input:
    external: true
  metadata:
    external: true
  cookies:
    external: true
