# version: "3.9"
---
services:
  telegram_youtube_bot:
    build: ./telegram_youtube_bot
    args: [PUID=${PUID}, PGID=${PGID}]
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_IDS=${TELEGRAM_ADMIN_IDS}
      - YT_DLP_COOKIES_FILE=${YT_DLP_COOKIES_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - DOMAIN=${DOMAIN}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - input:/input
      - metadata:/metadata
      - cookies:/cookies:rw
    networks:
      - backend

volumes:
  input:
    external: true
  metadata:
    external: true
  cookies:
    external: true

networks:
  backend:
    external: true
